version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: dockerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    links:
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: dockerpassword
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  postgres-data: