version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: dockerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  percentage-mock:
    image: wiremock/wiremock:2.35.0
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - "8383:8080"
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - redis
      - percentage-mock
    links:
      - redis
      - percentage-mock
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: dockerpassword
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  postgres-data: