spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dockerdb
    username: dockeruser
    password: dockerpassword
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
retry:
  maxAttempts: 3
  delay: 100

percentage:
  client:
    url: localhost:3000/percentage

server:
  port: 8080

